AgendaDeContatos/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaDeContatos.Models
{
    public class Contexto : DbContext
    {
        public DbSet<Pessoa> Pessoas  { get; set; }

        public Contexto(DbContextOptions<Contexto> opcoes): base(opcoes)
        {

        }
    }
}

AgendaDeContatos/Models/ErrorViewModel.cs
using System;

namespace AgendaDeContatos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendaDeContatos/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaDeContatos.Models
{
    public class Pessoa
    {
        public int PessoaId { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório")]
        [EmailAddress(ErrorMessage = "Email Invalido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório")]
        public string Telefone { get; set; }
    }
}

AgendaDeContatos/Controllers/PessoasController.cs
using AgendaDeContatos.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaDeContatos.Controllers
{
    public class PessoasController : Controller
    {
        private readonly Contexto _contexto;
      
        public PessoasController(Contexto contexto)
        {
            _contexto = contexto;
        }
        public async Task<IActionResult> IndexAsync()
        {
            return View(await _contexto.Pessoas.ToListAsync());
        }

        [HttpGet]
        public IActionResult CriarPessoa()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriarPessoa(Pessoa pessoa)
        {
            if(ModelState.IsValid)
            { 
                _contexto.Add(pessoa);
                await _contexto.SaveChangesAsync();
                TempData["ContatoNovo"] = $"Contato com nome {pessoa.Nome} incluido com sucesso";
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        [HttpGet]
        public async Task<IActionResult> AtualizarPessoa(int pessoaId)
        {
            Pessoa pessoa = await _contexto.Pessoas.FindAsync(pessoaId);

            if (pessoa == null)

                return NotFound();

            return View(pessoa);
        }

        [HttpPost]
        public async Task<IActionResult> AtualizarPessoa(Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                _contexto.Update(pessoa);
                await _contexto.SaveChangesAsync();
                TempData["ContatoAtualizado"] = $"Contato com nome {pessoa.Nome} atualizado com sucesso";
                return RedirectToAction(nameof(Index));
            }

            return View(pessoa);
        }

        [HttpPost]
        public async Task<JsonResult> ExcluirPessoa(int pessoaId)
        {
            Pessoa pessoa = await _contexto.Pessoas.FindAsync(pessoaId);
            _contexto.Pessoas.Remove(pessoa);
            await _contexto.SaveChangesAsync();
            TempData["ContatoExcluido"] = $"Contato com nome {pessoa.Nome} excluido com sucesso";
            return Json(true);
        }
    }
}

AgendaDeContatos/Views/Pessoas/AtualizarPessoa.cshtml
@model AgendaDeContatos.Models.Pessoa

@{
    ViewData["Title"] = "Atualização do Cotato" + Model.Nome;
}


<h4>Atualização do Contato @Model.Nome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarPessoa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PessoaId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" id="telefone" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success" /> &emsp;
                <a asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#telefone").mask("(99) 99999-9999");
        });
    </script>
}

AgendaDeContatos/Views/Pessoas/CriarPessoa.cshtml
@model AgendaDeContatos.Models.Pessoa

@{
    ViewData["Title"] = "Novo Contato";
}


<h4>Novo Contato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CriarPessoa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" id="telefone" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success" /> &emsp;
                <a asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
   <script>
       $(document).ready(function () {
           $("#telefone").mask('(99) 99999-9999');
       });
       
   </script>
}

AgendaDeContatos/Views/Pessoas/Index.cshtml
@model IEnumerable<AgendaDeContatos.Models.Pessoa>

@{
    ViewData["Title"] = "Contatos Cadastratos";
}

<div class="alert alert-dark row align-content-center">
    <div class="col-10 align-content-start">
        <h6>@Model.Count() contatos cadastrados</h6>
    </div>
    <div class="col-2 align-content-end">
        <a asp-action="CriarPessoa" class="btn btn-sm btn-outline-dark">Novo Contato</a>
    </div>
</div>
<div>
    @if (TempData["ContatoNovo"] != null)
    {
        <p class="alert alert-success">@TempData["ContatoNovo"].ToString()</p>
    }
    @if (TempData["ContatoAtualizado"] != null)
    {
        <p class="alert alert-primary">@TempData["ContatoAtualizado"].ToString()</p>
    }
    @if (TempData["ContatoExcluido"] != null)
    {
        <p class="alert alert-danger">@TempData["ContatoExcluido"].ToString()</p>
    }
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                <a asp-action="AtualizarPessoa" asp-route-pessoaId="@item.PessoaId" class="btn btn-sm btn-outline-primary">Atualizar</a> |
                <a class="btn btn-sm btn-outline-danger" onclick="ConfirmarExclusao(@item.PessoaId, '@item.Nome')">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmaçõa de Exclusão</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Prosserguir com a exclusão do contato <text class="nomeContato"></text> ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary btnFechar" data-bs-dismiss="modal">Não</button>
                <button type="button" class="btn btn-outline-danger btnExcluir" data-bs-dismiss="modal">Sim</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>
        function ConfirmarExclusao(pessoaId, nomeContato) {
            $(".nomeContato").text(nomeContato);
            $(".modal").modal();

            $(".btnExcluir").on('click', function () {
                $.ajax({
                    url: 'Pessoas/ExcluirPessoa',
                    method: 'POST',
                    data: { pessoaId: pessoaId },
                    success: function (data) {
                        location.reload(true);
                    }
                });
            });

            $(".btnFechar").on('click', function () {
                pessoaId = null;
                nomeContato = null;
                $(".modal").modal('hide');
            })
        }
    </script>
}

AgendaDeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendaDeContatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pessoas" asp-action="Index">Agenda De Contatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Agenda De Contatos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"</script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>